# Generated by Django 6.0.3 on 2026-04-05 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Investigator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('badge_id', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrowserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('browser', models.CharField(max_length=50)),
                ('url', models.TextField()),
                ('title', models.TextField(blank=True, null=True)),
                ('visit_count', models.IntegerField(default=0)),
                ('typed_count', models.IntegerField(default=0)),
                ('scan_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mytool.case')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=300)),
                ('hash_value', models.CharField(blank=True, max_length=256, null=True)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytool.case')),
            ],
        ),
        migrations.CreateModel(
            name='FileEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('event_type', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('path', models.TextField()),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('extension', models.CharField(blank=True, max_length=20, null=True)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('modified_time', models.DateTimeField(blank=True, null=True)),
                ('accessed_time', models.DateTimeField(blank=True, null=True)),
                ('deleted_time', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('scan_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mytool.case')),
            ],
        ),
        migrations.CreateModel(
            name='ChainOfCustody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytool.evidence')),
                ('investigator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytool.investigator')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='investigator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytool.investigator'),
        ),
        migrations.CreateModel(
            name='WindowsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('event_type', models.CharField(max_length=100)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('process_name', models.TextField(blank=True, null=True)),
                ('event_id', models.IntegerField()),
                ('source', models.CharField(max_length=50)),
                ('scan_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mytool.case')),
            ],
        ),
    ]
